spring.application.name=AILogAnalyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_log_analyzer
spring.datasource.username=mac
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash